// compare-react/src/components/footer/Footer.jsx
import React from 'react';

import './footer.css';

const Footer = () => {
    return (
        <footer className="footer is-primary">
            <div className="container">
                <div className="columns">
                <div className="column">
                    <p>And this right here is a spiffy footer, where you can put stuff.</p>
                </div>
                <div className="column has-text-right">
                    <a className="icon"><i className="fa fa-facebook"></i></a>
                    <a className="icon"><i className="fa fa-twitter"></i></a>
                </div>
                </div>
            </div>
        </footer>
    );
};

export default Footer;

// compare-vue/src/components/Footer.vue
<template>
  <footer class="footer is-primary">
      <div class="container">
        <div class="columns">
          <div class="column">
            <p>And this right here is a spiffy footer, where you can put stuff.</p>
          </div>
          <div class="column has-text-right">
            <a class="icon" href="#"><i class="fa fa-facebook"></i></a>
            <a class="icon" href="#"><i class="fa fa-twitter"></i></a>
          </div>
        </div>
      </div>
    </footer>
</template>

<script>
export default {
  name: 'footer',
};
</script>

<style lang="scss" scoped>
@import "../main.scss";

.footer {
  background-color: $primary;

  .icon {
    color: #fff;
    margin-left: 20px;
  }
}
</style>
