// compare-react/src/App.jsx
import React, { Component } from 'react';
import Header from './components/header/Header';
import Footer from './components/footer/Footer';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <Header />

        <Footer />
      </div>
    );
  }
}

export default App;

// compare-vue/src/App.vue
<template>
  <div id="app">
    <v-header></v-header>

    <router-view></router-view>

    <v-footer></v-footer>
  </div>
</template>

<script>
import Header from './components/Header';
import Footer from './components/Footer';

export default {
  name: 'app',
  components: {
    'v-header': Header,
    'v-footer': Footer,
  },
};
</script>
