// compare-vue/src/components/Header.vue
<template>
  <header class="nav has-shadow">
      <div class="container">
        <div class="nav-left">
          <router-link to="/" class="nav-item">My Company</router-link>
        </div>

        <span :class="['nav-toggle', { 'is-active': isActive }]"
              @click="toggleNav"
        >
          <span></span>
          <span></span>
          <span></span>
        </span>

        <div :class="['nav-right', 'nav-menu', { 'is-active': isActive }]">
          <nav v-for="(link, index) in routeLinks" :key="index">
            <router-link :to="link.route" class="nav-item r-item">{{ link.text }}</router-link>
          </nav>

          <div class="nav-item">
            <p class="control">
              <a class="button is-primary is-outlined">
                <span class="icon">
                  <i class="fa fa-download"></i>
                </span>

                <span>Join Now</span>
              </a>
            </p>
          </div>
        </div>
      </div>
    </header>
</template>

<script>
export default {
  name: 'header',
  data: () => ({
    routeLinks: [
      { route: '/', text: 'Home' },
      { route: '/faq', text: 'Features' },
      { route: '/faq', text: 'About' },
      { route: '/faq', text: 'Faq' },
    ],
    isActive: false,
  }),
  methods: {
    toggleNav() {
      this.isActive = !this.isActive;
    },
  },
};
</script>

<style lang="scss" scoped>
@import '../main.scss';

.nav {
  background-color: #3b3b3b;

  a:hover {
    color: gray;
  }

  &-left a{
    color: #fff;
    font-weight: bold;
  }

  .r-item {
    color: #c1c1c1;
    padding: .5rem 1.75rem;

    @include mobile {
      color: gray;
      &:hover {
        background-color: #f1f1f1;
      }
    }
  }

  &-toggle {
    span {
      background-color: #c1c1c1;
    }
  }
}
</style>

// compare-react/src/components/header/Header.jsx
import React, { Component } from 'react';
import './header.css';
import { Link } from 'react-router-dom';

class Header extends Component {
    render() {
        return (
            <header className="nav has-shadow">
                <div className="container">
                    <div className="nav-left">
                        <Link to="/" className="nav-item">My Company</Link>
                    </div>

                    {/*<span :class="['nav-toggle', { 'is-active': isActive }]" @click="toggleNav">*/}
                    <span className="nav-toggle">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>

                    {/*<div :class="['nav-right', 'nav-menu', { 'is-active': isActive }]">*/}
                    <div className="nav-right nav-menu">
                        <Link to="/" className="nav-item r-item">Home</Link>
                        <Link to="/faq" className="nav-item r-item">Features</Link>
                        <Link to="/faq" className="nav-item r-item">About</Link>
                        <Link to="/faq" className="nav-item r-item">Faq</Link>

                        <div className="nav-item">
                            <p className="control">
                                <a className="button is-primary is-outlined">
                                    <span className="icon">
                                        <i className="fa fa-download"></i>
                                    </span>
                                    <span>Join Now</span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </header>
        );
    }
}

export default Header;
